### PR TITLE
Clean up and switched several categories from CreateCapCategory -> CreateCapCategoryWithDataTypes

### PR DESCRIPTION
**Pull request by mohamed-barakat**

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
This PR affects `ZXCalculusForCAP`. I will prepare a subset of it that does not affect `ZXCalculusForCAP`.

**Comment by mohamed-barakat** [comment]
> This PR affects `ZXCalculusForCAP`. I will prepare a subset of it that does not affect `ZXCalculusForCAP`.

It turns out that `ZXCalculusForCAP` (https://github.com/homalg-project/ZXCalculusForCAP/commit/418df332ea04340e58e183ac71061a70c7883c6f) behaves in the same way as with Fabian's PR https://github.com/homalg-project/CategoricalTowers/pull/264, that was merged 4 days ago.

So I will merge this PR.

**Comment by zickgraf** [comment]
> This PR affects `ZXCalculusForCAP`. I will prepare a subset of it that does not affect `ZXCalculusForCAP`.

Sorry, what you're seeing probably is that ZXCalculusForCAP is compiled with https://github.com/zickgraf/CategoricalTowers/tree/compilability.

**Comment by zickgraf** [comment]
Very nice, this is a big step in making data types mandatory.

Regarding the first commit: The concept of cell filters per category is incompatible with the Julia conversion because the object and morphism filters then have to be defined via `and` for filters. `IsCellInAlgebroidFromDataTables` seems to not be used in the code, so I suggest to simply remove it.

**Comment by mohamed-barakat** [comment]
> Sorry, what you're seeing probably is that ZXCalculusForCAP is compiled with https://github.com/zickgraf/CategoricalTowers/tree/compilability.

I see, thanks for the hint.

**Comment by mohamed-barakat** [comment]
> Regarding the first commit: The concept of cell filters per category is incompatible with the Julia conversion because the object and morphism filters then have to be defined via `and` for filters. `IsCellInAlgebroidFromDataTables` seems to not be used in the code, so I suggest to simply remove it.

I have a parent cell filter for convenience at several places (mainly to avoid code duplication). If we decide to eliminate them we should discuss alternatives to avoid code duplication.

**Comment by zickgraf** [comment]
> I have a parent cell filter for convenience at several places (mainly to avoid code duplication). If we decide to eliminate them we should discuss alternatives to avoid code duplication.

We can look at some examples together. Many of those convenience methods I have seen are not compatible with CompilerForCAP, sometimes because they are simply wrong in the sense that they would not really apply to two cells and only by chance objects and morphisms can be handled in the same way. In this case, syntactical code duplication is not necessarily semantic code duplication.

**Comment by mohamed-barakat** [comment]
> We can look at some examples together. Many of those convenience methods I have seen are not compatible with CompilerForCAP, sometimes because they are simply wrong in the sense that they would not really apply to two cells and only by chance objects and morphisms can be handled in the same way. In this case, syntactical code duplication is not necessarily semantic code duplication.

Very nice, I agree.

**Pull request merged**
