### PR TITLE
preload FinSetsForCAP before FreydCategoriesForCAP in tests

### PR DESCRIPTION
**Pull request by mohamed-barakat**
to have the full functionality of `FreydCategoriesForCAP`

and before `FinSetsForCAP` preload `CategoryConstructor` (future `ToolsForCategoricalTowers`)

to have the full functionality of FinSetsForCAP

### CODE REVIEW

**Comment by kamalsaleh** [comment]
I think `FunctorCategories` and `FiniteCocompletions` need to be adjusted as well as both precall `FreydCategories`.

**Comment by kamalsaleh** [comment]
Note: locally when I preload `FinSetsForCAP` in `FiniteCocompletions`, the following happens:

 ```
gap> FinBouquets;
 gap> Chat := ModelingCategory( FinBouquets );
 gap> ColimitQuiversC := CategoryOfColimitQuivers( UnderlyingCategory( FinBouquets ) );
 gap> P := ColimitQuiversC.P;
 gap> b := ColimitQuiversC.b;
 Error, no method found! For debugging hints type ?Recovery from NoMethodFound
 Error, no 1st choice method found for `Limit' on 3 arguments at /home/kamal/Software/gap/lib/methsel2.g:250 called  from
Limit( H, hom_diagram[1], hom_diagram[2] 
 ) at /home/kamal/
```

**Comment by mohamed-barakat** [comment]
> Note: locally when I preload `FinSetsForCAP` in `FiniteCocompletions`, the following happens:
> 
> ```
> gap> FinBouquets;
> gap> Chat := ModelingCategory( FinBouquets );
> gap> ColimitQuiversC := CategoryOfColimitQuivers( UnderlyingCategory( FinBouquets ) );
> gap> P := ColimitQuiversC.P;
> ```

I see, this is because `FinSetsForCAP` is lacking the limits in `CategoryConstructor` (future `ToolsForCategoricalTowers`).

**Comment by mohamed-barakat** [comment]
> I see, this is because `FinSetsForCAP` is lacking the limits in `CategoryConstructor` (future `ToolsForCategoricalTowers`).

Just forced pushed an update to this PR, please try again.

**Pull request merged**
