### PR TITLE
Added an option to sort morphisms of externals homs in PathCategories similar to QPA

### PR DESCRIPTION
**Pull request by kamalsaleh**
Example:

```
LoadPackage( "Algebroids" );

q_string := "q(o)[x:o->o,y:o->o,z:o->o]";

C := PathCategory( FinQuiver( q_string ) : sort_external_homs_like_qpa := true );
F := FreeCategory( RightQuiver( q_string ) );

qC := C / [ [C.x^3, C.x], [C.y^3, C.y], [C.z^3, C.z], [C.xy, C.yx], [C.xz, C.zx], [C.yz, C.zy] ];
qF := F / [ [F.x^3, F.x], [F.y^3, F.y], [F.z^3, F.z], [F.xy, F.yx], [F.xz, F.zx], [F.yz, F.zy] ];

MorphismsOfExternalHom( qC.o, qC.o );
#  [ [id(o)]:(o) -≻ (o), [x]:(o) -≻ (o), [y]:(o) -≻ (o),  ..., [x^2⋅y^2⋅z^2]:(o) -≻ (o) ]
MorphismsOfExternalHom( qF.o, qF.o );
#  [ (o)-[(o)]->(o), (o)-[(x)]->(o), (o)-[(y)]->(o), ..., (o)-[(x*x*y*y*z*z)]->(o) ]

```
Bump FpCategories to V2024.04-01

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
Thank you very much. Could you please add the above example in an example file that covers the new code? Mabye you just forgot to `git add` it :)

**Comment by kamalsaleh** [comment]
Done!

**Comment by mohamed-barakat** [comment]
The tests took an hour longer than usual. I will restart them. In case the regression remains I will ping you.

**Comment by kamalsaleh** [comment]
It seems there is a problem in uploading the code-coverage:

```
['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
[2024-04-11T10:18:31.615Z] ['verbose'] The error stack is: Error: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
    at main (/snapshot/repo/dist/src/index.js)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-04-11T10:18:31.615Z] ['verbose'] End of uploader: 1060 milliseconds
Codecov upload failed, retrying in 60s
```

I will remove the current commit and try a phantom commit to see if my code somehow causes this issue.

**Comment by kamalsaleh** [comment]
Uploading the **code-coverage** fails many times (and eventually succeeds) as expected irrelevant of my commit. It looks like a Github issue and might be resolved after few days. I have understood from Fabian that uploading the **code-coverage** is enabled only on _gap-docker-master_ for pull-requests or merges; and is disabled in the _gap-docker_ and all _nighty tests_.  The same behaviour has been happining for few days in [CAP_Project](https://github.com/homalg-project/CAP_project/actions). Hence, I will re-push the original commit. It might take time until tests pass but still it can then be merged.

**Comment by mohamed-barakat** [comment]
Thanks for the commit and the investigation :)

**Pull request merged**
