### PR TITLE
fixed ApplyMorphismInPreSheafCategoryToObject

### PR DESCRIPTION
**Pull request by kamalsaleh**

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
As you see, there are more bugs that I fixed in `FunctorCategories` and am planning to port them here.

**Comment by mohamed-barakat** [comment]
I am not yet decided whether to make pair[2] take one or three arguments. With one argument simplifies some of the code, but then I run into the inability to check the equality of objects needed in PreCompose etc. I have to see if this problem disappears with the three argument alternative.

**Comment by mohamed-barakat** [comment]
In the meantime, you can use my `functional` branch on `FunctorCategories`. There, pair[2] consistently takes one argument.

**Comment by kamalsaleh** [comment]
I am in favor of keeping the current behavior, where the function `pair[2]` takes three arguments: `s, morphism, r`, because then, I would not be forced to always construct `s := presheaf_on_objects( Range( morphism ) )` and `r := presheaf_on_morphisms( Source(morphism) )` every time I implement a function for `pair[2]`. For example, here:

https://github.com/kamalsaleh/HigherHomologicalAlgebra/blob/5caaa0ecc182878b9a79952425f4ef16d77ba2bc/DerivedCategories/gap/Functors.gi#L24-L34

**Comment by kamalsaleh** [comment]
The CI-error is caused by the same issue. Maybe we can decide tomorrow which variant is better.

**Comment by mohamed-barakat** [comment]
> I am in favor of keeping the current behavior, where the function `pair[2]` takes three arguments: `s, morphism, r`, because then, I would not be forced to always construct `s := presheaf_on_objects( Range( morphism ) )` and `r := presheaf_on_morphisms( Source(morphism) )` every time I implement a function for `pair[2]`. For example, here:
> 
> https://github.com/kamalsaleh/HigherHomologicalAlgebra/blob/5caaa0ecc182878b9a79952425f4ef16d77ba2bc/DerivedCategories/gap/Functors.gi#L24-L34

You can use the variant `WihtoutGivenObjects` for the moment.

**Comment by mohamed-barakat** [comment]
Preceded by https://github.com/homalg-project/CategoricalTowers/pull/7.

**Comment by mohamed-barakat** [comment]
> Maybe we can decide tomorrow which variant is better.

Yes, we should discuss this together with @zickgraf.

**Pull request closed without merging**
