### PR TITLE
remove test Opposite( SkeletalFinSets ) from Toposes

### PR DESCRIPTION
**Pull request by mohamed-barakat**

### CODE REVIEW

**Comment by zickgraf** [comment]
Maybe it would make sense to keep the test but use the terminal category instead of SkeletalFinSets.

**Comment by mohamed-barakat** [comment]
> Maybe it would make sense to keep the test but use the terminal category instead of SkeletalFinSets.

The terminal category has little to do with Toposes. What about moving this test to `FinSetsForCAP`?

**Comment by zickgraf** [comment]
> The terminal category has little to do with Toposes.

Mathematically yes. However, I assume that the purpose of this test is to check that all categorical properties of Toposes are correctly dualized. For this, from a technical standpoint the terminal category is well-suited and does not cause any dependency cycles because it is included in CAP.

**Comment by mohamed-barakat** [comment]
> Mathematically yes. However, I assume that the purpose of this test is to check that all categorical properties of Toposes are correctly dualized. For this, from a technical standpoint the terminal category is well-suited and does not cause any dependency cycles because it is included in CAP.

The terminal category is not appropriate for this test since it has each property along with its dual property.

**Comment by zickgraf** [comment]
I have thought more about this: Why not use a dummy category? This allows to cover the technical part in Toposes, while the mathematical test can be moved to FinSetsForCAP.

**Pull request merged**
