### PR TITLE
added is_computable to category_constructor_options in the constructor PreSheaves

### PR DESCRIPTION
**Pull request by mohamed-barakat**
in compliance with PR https://github.com/homalg-project/CAP_project/pull/1379

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
@kamalsaleh: The CI is failing in Algebroids, could you please have a look?

**Comment by kamalsaleh** [comment]
`PSh!.is_computable := true;` 

should be inserted in this code-chunk:

https://github.com/homalg-project/CategoricalTowers/blob/ce96f186a8e0596c018d553f20ebbacbab39af00/Algebroids/gap/AlgebroidFromDataTables.gi#L1581C1-L1592C17

**Comment by mohamed-barakat** [comment]
> `PSh!.is_computable := true;`
> 
> should be inserted in this code-chunk:
> 
> https://github.com/homalg-project/CategoricalTowers/blob/ce96f186a8e0596c018d553f20ebbacbab39af00/Algebroids/gap/AlgebroidFromDataTables.gi#L1581C1-L1592C17

Thank you very much, done.

**Comment by mohamed-barakat** [comment]
@zickgraf: DuplicateFreeList is not supported in Juila's emulation of GAP.

**Comment by zickgraf** [comment]
> @zickgraf: DuplicateFreeList is not supported in Juila's emulation of GAP.

Fixed: https://github.com/zickgraf/CAP.jl/commit/bc67f87430dc652ab42163aae7d0c2cf60e551d9 I have restarted the CI.

**Comment by mohamed-barakat** [comment]
Wonderful, thank you very much.

**Pull request merged**
