### PR TITLE
Apply PackageJanitor

### PR DESCRIPTION
**Pull request by zickgraf**

### CODE REVIEW

**Comment by zickgraf** [comment]
If the CI succeeds this is now ready for merge.

**Comment by zickgraf** [comment]
The CI now catches problems when creating the subsplits and has already found a problem with CatReps which went unnoticed before. The fix is (probably) the same as in https://github.com/homalg-project/CategoricalTowers/pull/94. I will create a PR.

**Comment by zickgraf** [comment]
Finally everything is green and reasonably fast :-) (of course modulo the actual tests which take about an hour :D )

**Comment by mohamed-barakat** [comment]
Thank you very much.

**Pull request merged**
