### PR TITLE
Adjust to various changes in CAP_project

### PR DESCRIPTION
**Pull request by zickgraf**

### CODE REVIEW

**Comment by zickgraf** [comment]
@mohamed-barakat I have fixed most of the problems and have also pushed a temporary commit to adjust to https://github.com/homalg-project/CAP_project/pull/1623. However, some unexpected issues remain, for example a difference in the compilation in `CategoryFromNerveData` which I cannot reproduce locally. Maybe you could have a look?

**Comment by mohamed-barakat** [comment]
Could you also turn the first commit into PR with new versions and bumped dependencies?

**Comment by mohamed-barakat** [comment]
The constructor `ReinterpretationOfCategory` is failing to `SetRangeCategoryOfHomomorphismStructure` in the `only_primitive_operations := true`-case.

**Comment by zickgraf** [comment]
> The constructor `ReinterpretationOfCategory` is failing to `SetRangeCategoryOfHomomorphismStructure` in the `only_primitive_operations := true`-case.

This case works well for `CategoryOfColumns_as_Opposite_CategoryOfRows`.  Also, there were no changes to `ReinterpretationOfCategory`, were there? Hence I don't expect `ReinterpretationOfCategory` to be the culprit.

**Comment by mohamed-barakat** [comment]
The difference is that in the failing case the input category has a derived Hom-structure.

**Comment by zickgraf** [comment]
It looks like the code of `ReinterpretationOfCategory` has not changed since January: https://github.com/homalg-project/CAP_project/commits/master/CAP/gap/ReinterpretationOfCategory.gi

**Comment by mohamed-barakat** [comment]
Many thanks :)

**Pull request merged**
