### PR TITLE
d&i SourceOfUnderlyingMorphism for slice category objects

### PR DESCRIPTION
**Pull request by mohamed-barakat**
and used it to simplify code.

* SourceOfUnderlyingMorphism replaces UnderlyingCell for slice category objects
* UnderlyingCell is now only installed for slice category morphisms

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
@zickgraf: The last commit seems to affect `ZXCalculusForCAP`.

**Comment by zickgraf** [comment]
> I now use `SourceOfUnderlyingMorphism` instead of `UnderlyingObject`. Now there is no effect on `ZXCalculusForCAP`.

Yes, that's a good solution, also for readability, I think. Thanks for checking! Using something both as an attribute and as an operation which should be resolved by the compiler confuses the compiler. Not in the sense that the result would be wrong but in the sense that unnecessary warnings are displayed.

**Comment by mohamed-barakat** [comment]
I am happy we now have `ZXCalculusForCAP` as one more compiled tower. At some point, it could be tested with `CategoricalTowers` like `FinSetsForCAP`.

BTW:

* When I execute the precompile-file in `ZXCalculusForCAP` I get warnings, e.g., regarding `PositionsProperty`, that you are probably aware of.
* I am working on replacing (almost) all `CreateCapCategory` in `CategoricalTowers` with `CreateCapCategoryWithDataTypes`.

**Comment by zickgraf** [comment]
> I am happy we now have `ZXCalculusForCAP` as one more compiled tower. At some point, it could be tested with `CategoricalTowers` like `FinSetsForCAP`.
> 
> BTW:
> 
>     * When I execute the precompile-file in `ZXCalculusForCAP` I get warnings, e.g., regarding `PositionsProperty`, that you are probably aware of.

Yes, that is one of the reasons why the code is not yet automatically precompiled in the tests.

>     * I am working on replacing (almost) all `CreateCapCategory` in `CategoricalTowers` with `CreateCapCategoryWithDataTypes`.

Nice :-) We also have to adapt CAP's `CategoryConstructor` for this.

**Pull request merged**
